workflows:
  android-release:
    name: Android Release
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Clean and rebuild
        script: |
          flutter clean
          flutter pub get
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
