workflows:
  android-release:
    name: Android Release
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Clean everything
        script: |
          rm -rf android/
          rm -rf ios/
          rm -rf build/
          flutter create --platforms=android --org=com.ram .
          flutter pub get
      - name: Build Android APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
