name: ram_wallet
description: Gestion financière personnelle - Salaires, dépenses, dettes
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Base de données et stockage
  shared_preferences: ^2.2.3
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  
  # UI et dates
  cupertino_icons: ^1.0.8
  table_calendar: ^3.1.2
  intl: ^0.19.0
  
  # Graphiques
  fl_chart: ^0.68.0
  
  # Utilitaires
  uuid: ^4.3.3
  logger: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
